apiVersion: v1
kind: Pod
metadata:
  name: dev
  labels:
    tier: dev
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "demo", "name":"red-net"}'
  }
spec:
  containers:
    - name: dev
      image: savvythru/web-app-dev
      ports:
      - containerPort: 80
