apiVersion: v1
kind: Pod
metadata:
  name: ubuntuapp-custom
  labels:
    app: ubuntuapp-custom
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "qa", "name":"red-network"}'
  }
spec:
  containers:
    - name: ubuntuapp-custom
      image: ubuntu-upstart
