apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    tier: db
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "redmine", "name":"database-network"}'
  }
spec:
  containers:
    - name: database
      image: mysql
      env:
        - name: MYSQL_DATABASE
          value: redmine
        - name: MYSQL_ROOT_PASSWORD
          value: secret
